CREATE TABLE MOVIE (
    ID BIGINT,
    CONSTRAINT PRIMARY KEY ID_MOVIE (ID),
    TITLE NVARCHAR(50) NOT NULL UNIQUE,
    DIRECTOR NVARCHAR(20) NOT NULL,
    YEAR INT CHECK (YEAR BETWEEN 1900 AND 2023),
    LENGTH_MINS INT CHECK (LENGTH_MINS BETWEEN 10 AND 200)
);

CREATE TABLE MOVIE_STAT (
    ID BIGINT,
    CONSTRAINT PRIMARY KEY ID_MOVIE_STAT (ID),
    RATING DECIMAL(3 , 1 ) CHECK (RATING BETWEEN 1 AND 10),
    DOMESTIC_SALES INT,
    INTERNATIONAL_SALES INT
);

-------------

SELECT DIRECTOR, count(*) FROM movie
group by DIRECTOR;

select DIRECTOR,  sum(DOMESTIC_SALES), sum(INTERNATIONAL_SALES) from movie_stat, movie
where movie_stat.ID = movie.ID
group by movie.DIRECTOR;

select DIRECTOR, sum(DOMESTIC_SALES), sum(INTERNATIONAL_SALES) from movie
join movie_stat on movie_stat.ID = movie.ID
group by DIRECTOR;

------------
select * from movie
order by YEAR desc;

select * from movie_stat
order by INTERNATIONAL_SALES desc;