
CREATE TABLE forum_categories (
    ID BIGINT,
    CONSTRAINT categories_pk PRIMARY KEY (ID),
    TITLE VARCHAR(64),
    DESCRIPTION TEXT,
    DATE TIMESTAMP,
    IP VARCHAR(20)
);

CREATE TABLE forum_subcategories (
    ID BIGINT,
    CONSTRAINT subcategories_pk PRIMARY KEY (ID),
    ID_CATEGORY BIGINT,
    CONSTRAINT ID_CATEGORY FOREIGN KEY (ID_CATEGORY)
        REFERENCES forum_categories (ID),
    TITLE VARCHAR(45),
    DESCRIPTION TEXT,
    DATE TIMESTAMP,
    IP VARCHAR(20)
);

CREATE TABLE users (
    ID BIGINT,
    CONSTRAINT users_pk PRIMARY KEY (ID),
    NICK VARCHAR(16),
    PASSWORD VARCHAR(128),
    EMAIL VARCHAR(128),
    DATE TIMESTAMP,
    KARMA DECIMAL(9 , 2 ),
    IP VARCHAR(20)
);


CREATE TABLE forum_polls_options (
    ID BIGINT,
    CONSTRAINT forum_polls_options_pk PRIMARY KEY (ID),
    ID_POST BIGINT,
    CONSTRAINT ID_POST FOREIGN KEY (ID_POST)
        REFERENCES forum_posts (ID),
    TITLE VARCHAR(64),
    DATE TIMESTAMP
);

CREATE TABLE forum_posts (
    ID BIGINT,
    CONSTRAINT forum_posts_pk PRIMARY KEY (ID),
    ID_SUBCATEGORY BIGINT,
    CONSTRAINT ID_SUBCATEGORY FOREIGN KEY (ID_SUBCATEGORY)
        REFERENCES forum_subcategories (ID),
    ID_USER BIGINT,
    CONSTRAINT ID_USER FOREIGN KEY (ID_USER)
        REFERENCES users (ID),
    PARENT_POST BIGINT,
    CONSTRAINT PARENT_POST FOREIGN KEY (PARENT_POST)
        REFERENCES forum_posts (ID),
    TITLE VARCHAR(90),
    CONTENT TEXT,
    IS_POLL BOOLEAN,
    DATE TIMESTAMP,
    IP VARCHAR(20)
);

----------------------

CREATE TABLE forum_polls_options_votes (
    ID BIGINT,
    CONSTRAINT forum_polls_options_votes_pk PRIMARY KEY (ID),
    ID_POLL_OPTION BIGINT,
    CONSTRAINT ID_POLL_OPTION FOREIGN KEY (ID_POLL_OPTION)
        REFERENCES forum_polls_options (ID),
    ID_USER BIGINT,
    CONSTRAINT ID_USER FOREIGN KEY (ID_USER)
        REFERENCES users (ID),
    DATE TIMESTAMP,
    IP VARCHAR(20)
);



