 CREATE TABLE AUTHOR (
    ID BIGINT,
    CONSTRAINT AUTHOR_PK PRIMARY KEY (ID),
    NAME NVARCHAR(50) NOT NULL,
    LAST_NAME NVARCHAR(50) UNIQUE,
    COUNTRY NVARCHAR(50) DEFAULT 'ENGLAND',
    AGE BIGINT DEFAULT 0,
    ARTICLES_COUNT BIGINT CHECK (ARTICLES_COUNT > 10),
    CONSTRAINT CHECK_COUNTRY CHECK (COUNTRY != 'CHINE'
        AND LAST_NAME != 'TEST_LN')
);
