  CREATE TABLE HOTEL (
    ID BIGINT,
    CONSTRAINT HOTEL_ID PRIMARY KEY (ID),
    COUNTRY NVARCHAR(50) DEFAULT 'N/A',
    CITY NVARCHAR(50) NOT NULL,
    STREET NVARCHAR(50),
    CONSTRAINT TEST_COUNTRY CHECK (COUNTRY != 'Romania'
        AND COUNTRY != 'China'
        AND COUNTRY != 'Russia'
        AND COUNTRY != 'Belgium')
);

   CREATE TABLE ORDERS (
     ID BIGINT CHECK (ID < 10000),
     CONSTRAINT ORDER_ID PRIMARY KEY (ID),
     USER_ID BIGINT UNIQUE,
     ROOM_ID BIGINT UNIQUE,
     DATE_FROM TIMESTAMP,
     DATE_TO TIMESTAMP,
     MONEY_PAID DECIMAL(10 , 2 )
 );